version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: changeinprod
      POSTGRES_DB: booking
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
